customhost = "employee.cvodm9afoekj.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "bait3273"
customdb = "employee"
custombucket = "tanmingkit-bucket"
customregion = "us-east-1"